/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutWordListIndexImport } from './routes/_layout/word-list/index'
import { Route as LayoutWordSlugImport } from './routes/_layout/word/$slug'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWordListIndexRoute = LayoutWordListIndexImport.update({
  id: '/word-list/',
  path: '/word-list/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutWordSlugRoute = LayoutWordSlugImport.update({
  id: '/word/$slug',
  path: '/word/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/word/$slug': {
      id: '/_layout/word/$slug'
      path: '/word/$slug'
      fullPath: '/word/$slug'
      preLoaderRoute: typeof LayoutWordSlugImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/word-list/': {
      id: '/_layout/word-list/'
      path: '/word-list'
      fullPath: '/word-list'
      preLoaderRoute: typeof LayoutWordListIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWordSlugRoute: typeof LayoutWordSlugRoute
  LayoutWordListIndexRoute: typeof LayoutWordListIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWordSlugRoute: LayoutWordSlugRoute,
  LayoutWordListIndexRoute: LayoutWordListIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/word/$slug': typeof LayoutWordSlugRoute
  '/word-list': typeof LayoutWordListIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/word/$slug': typeof LayoutWordSlugRoute
  '/word-list': typeof LayoutWordListIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/word/$slug': typeof LayoutWordSlugRoute
  '/_layout/word-list/': typeof LayoutWordListIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/word/$slug' | '/word-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/word/$slug' | '/word-list'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/word/$slug'
    | '/_layout/word-list/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/word/$slug",
        "/_layout/word-list/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/word/$slug": {
      "filePath": "_layout/word/$slug.tsx",
      "parent": "/_layout"
    },
    "/_layout/word-list/": {
      "filePath": "_layout/word-list/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
